CREATE TABLE BOOK
(
    LOCATION    VARCHAR2(100)   NOT NULL,
    NOTE        VARCHAR2(100)   NOT NULL,
    REG_DT      DATE            NOT NULL,
    REG_AMT     NUMBER(100)     NOT NULL,
    PRIMARY KEY (LOCATION, NOTE, REG_DT, REG_AMT)
);